siftdown:
	python3 02_merge_search_lists.py
	python3 03_filter_titles.py
	python3 04_openaccess_filter.py
	python3 05_abstract_enrichment.py
	python3 06_filter_by_abstract.py
	python3 07_ollama_filter.py
	python3 08_filter_titles.py
	python3 09_final_human_review.py

after_abstracts:
	python3 06_filter_by_abstract.py
	python3 07_ollama_filter.py
	python3 08_filter_titles.py
	python3 09_final_human_review.py
